### ISSUE TITLE
应用闪退

### ISSUE THREAD

**Issue by karlf168** [asd4134365/DingClock#3]
应用闪退，是什么原因？ 荣耀手机

**Comment by asd4134365** [comment]
可能是权限或安全导致问题
现在的钉钉可能需要修改代码匹配按钮文字

**Comment by karlf168** [comment]
> 可能是权限或安全导致问题
> 现在的钉钉可能需要修改代码匹配按钮文字

重新编译之后 不再闪退，现在是需要修改代码匹配按钮文字，能再更新一版吗？

**Comment by asd4134365** [comment]
不好意思暂时没什么时间弄这个...

是说无法自动进入打卡界面点击打卡吗？
这个有可能是手机适配问题，得具体手机具体看了

如果程序可以按设定时间自动打开钉钉，那么钉钉开启极速打卡，简单修改代码也可以实现自动打卡

**Comment by karlf168** [comment]
> 不好意思暂时没什么时间弄这个...
> 是说无法自动进入打卡界面点击打卡吗？
> 这个有可能是手机适配问题，得具体手机具体看了
> 如果程序可以按设定时间自动打开钉钉，那么钉钉开启极速打卡，简单修改代码也可以实现自动打卡

是无法自动进入打卡界面点击打卡，同时极速打卡没法开启。修改代码，没有这个能力。

**Comment by asd4134365** [comment]
更新了代码，你试试吧
/app/src/main/java/atorire/dingclock/DingClockService.java，line：113，“工作”改为了”工作台”

**Comment by karlf168** [comment]
> 更新了代码，你试试吧
> /app/src/main/java/atorire/dingclock/DingClockService.java，line：113，“工作”改为了”工作台”

1. 试了一下，不是”工作台“，还应该是“工作”。问题主要出现在，上班打卡和下班打卡按钮上。用System.out.println 怎么才能输出打卡页面中所有可以点击按钮的node的文本描述？
2. 比如下午是下班打卡，他应该找到下班打卡按钮点击才对；但是现在是找到了上班打卡，他就不往下找了，并且这个上班打卡的node并不是一个可以点击的按钮。这该如何解决呢？

**Comment by asd4134365** [comment]
我测试的钉钉版本是 5.0.15，昨天可以正常打卡，今天早晨是卡在健康打卡界面没有退出，这是因为新版本和以前打卡成功提示信息不一样了，还得测一测

1. 在 DingClockService.java 里有一个方法 step_test() 可以在logcat输出界面中所有的node，里面有clickable字段标识是否可点击。
比如要看打卡界面有哪些node，可以将step_test()加入step3_doCheckIn()方法第一行，运行程序在logcat就可以看到了。
也可以通过 node.isClickable() 判断是否可以点击
logcat找不到的话，它在 android studio 的 view 菜单 tool windows 下 Logcat

2. 上午下午的判断在DingClockService.java，line：172，应该是可以自动点击的

**Comment by asd4134365** [comment]
测了下现在打卡完毕后还存在没有回到指定界面的问题，我找时间改改代码吧。。

**Comment by karlf168** [comment]
> 测了下现在打卡完毕后还存在没有回到指定界面的问题，我找时间改改代码吧。。

是的，现在打卡是可以了，但回不了主页面，第二次打卡就打不上了。

**Comment by karlf168** [comment]
> 测了下现在打卡完毕后还存在没有回到指定界面的问题，我找时间改改代码吧。。

现在，第一次打卡可以，之后打卡就打不了，但是程序删除重新安装之后又可以重新打卡。而这不能实现自动打卡。

**Comment by karlf168** [comment]
> 测了下现在打卡完毕后还存在没有回到指定界面的问题，我找时间改改代码吧。。
> 
> 现在，第一次打卡可以，之后打卡就打不了，但是程序删除重新安装之后又可以重新打卡。而这不能实现自动打卡。

可以打卡了。 问题关闭了。 要是能回传打卡成功或是失败的消息就更好了
